const QUOTES_DATA = {
  Philosophy: [
    "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
    "In a gentle way, you can shake the world.",
    "Life is what happens when you're busy making other plans.",
    "The only way to solve a problem is to confront it.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "The cave you fear to enter holds the treasure you seek.",
    "Freedom is not something that one people can give to another as a gift.",
    "It is during our darkest moments that we must focus to see the light.",
    "In this moment, there is plenty of time.",
    "The question is not whether we can afford to invest in our children's future.",
    "We accept the love we think we deserve.",
    "Everything we know about ourselves might be wrong.",
    "You have to be odd to be number one.",
    "The way to get started is to quit talking and begin doing.",
    "Life is either a daring adventure or nothing at all.",
    "The biggest risk is not taking any risk.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "The purpose of our lives is to be happy.",
    "Get busy living or get busy dying.",
    "It is never too late to be what you might have been.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is our choices that show what we truly are.",
    "All we have to decide is what to do with the time that is given to us.",
    "We are only as sick as our secrets.",
    "There is no try, only do or do not.",
    "Your time is limited, don't waste it living someone else's life.",
    "Innovation distinguishes between a leader and a follower.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Success is not final, failure is not fatal.",
    "Be yourself; everyone else is already taken."
  ],
  Science: [
    "Imagination is more important than knowledge.",
    "Science is not a body of knowledge nor a belief system.",
    "The important thing is not to stop questioning.",
    "In science, there are no shortcuts to truth.",
    "Every particle of matter is attracted by or gravitated toward every other particle.",
    "The universe is a pretty big place.",
    "Science is the most reliable way of understanding the world.",
    "If you wish to make an apple pie from scratch, you must first invent the universe.",
    "Discovery consists of seeing what everybody has seen and thinking what nobody has thought.",
    "Science is organized knowledge.",
    "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood are made of starstuff.",
    "A scientist must also be mentally flexible and prepared to accept the possibility that his life work is wrong.",
    "The universe doesn't care about our limitations.",
    "Science knows no country, because knowledge belongs to humanity.",
    "The good thing about science is that it's true whether or not you believe in it.",
    "Nothing in biology makes sense except in the light of evolution.",
    "The effort to understand the universe is one of the very few things that lifts human life a little above the level of farce.",
    "Science is the belief in the ignorance of experts.",
    "The most incomprehensible thing about the world is that it is comprehensible.",
    "There are no shortcuts to any place worth going.",
    "We are made of star stuff.",
    "Science fiction is not just a collection of ideas.",
    "I am not afraid of anything anymore.",
    "We are an old species. We don't need to fear the future.",
    "Somewhere, something incredible is waiting to be known.",
    "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood, the carbon in our limbs, were all forged in ancient stars that exploded.",
    "Science is the only way we know to blow away mist and see through to reality.",
    "Science is a way of thinking much more than it is a body of knowledge.",
    "Somewhere, something incredible is waiting to be known.",
    "The cosmos is within us. We are made of star-stuff."
  ],
  Business: [
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Don't watch the clock; do what it does. Keep going.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    "Don't let what you cannot do interfere with what you can do.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You miss 100 percent of the shots you never take.",
    "Opportunities don't happen. You create them.",
    "Success is not about money. It's about making a difference.",
    "I find that the harder I work, the more luck I seem to have.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Don't compare yourself with others. Compare yourself with who you were yesterday.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You learn more from failure than from success.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Your limitation—it's only your imagination. Push beyond limitations.",
    "Great things never come from comfort zones.",
    "Dream bigger. Do bigger.",
    "Success doesn't just find you. You have to go out and get it.",
    "The only impossible journey is the one you never begin.",
    "In the middle of difficulty lies opportunity.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Don't watch the clock; do what it does. Keep going.",
    "The secret of getting ahead is getting started.",
    "Quality is not an act, it is a habit.",
    "One quality that every highly successful person shares is the willingness to work hard."
  ],
  Sports: [
    "You are never too old to set another goal or to dream a new dream.",
    "The master has failed more times than the beginner has even tried.",
    "Excellence is not a skill, it's an attitude.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Do not pray for an easy life, pray for the strength to endure a difficult one.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The only way to overcome it is to go through it.",
    "Pressure is a privilege.",
    "Your body can stand almost anything. It's your mind that needs convincing.",
    "Champions aren't made in gyms. Champions are made from something they have deep inside them.",
    "If you fail to prepare, you prepare to fail.",
    "The only way to do great work is to believe in what you're doing.",
    "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.",
    "It is not the mountain we conquer, but ourselves.",
    "Champions keep playing until they get it right.",
    "Winning isn't everything, but wanting to win is.",
    "To be a champion, you have to train like a champion.",
    "The difference between the impossible and the possible lies in a person's determination.",
    "I've missed more than 9000 shots in my career.",
    "You miss 100% of the shots you don't take.",
    "It's not the will to win that matters—everyone has that. It's the will to prepare to win that matters.",
    "Dedication is doing what you hate to do, but nonetheless doing it like you love it.",
    "Talent is a pursued interest. In other words, anything that you are willing to practice.",
    "The miracle isn't that I finished. The miracle is that I had the courage to start.",
    "If you think you can, you can. If you think you can't, you're right.",
    "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.",
    "You can't put a limit on anything. The more you dream, the farther you get.",
    "Do you know what my favorite part of the game is? The opportunity to play.",
    "The only place success comes before work is in the dictionary.",
    "Hard work beats talent when talent isn't working hard."
  ],
  Literature: [
    "It was the best of times, it was the worst of times.",
    "All that is gold does not glitter; not all those that wander are lost.",
    "We accept the love we think we deserve.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "You can't go back to how things were. How they were, they are no more.",
    "Silly girl, in the end we are our choices.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
    "Call me Ishmael.",
    "It was a pleasure to burn.",
    "The sun rose slowly, as if it had second thoughts about the day ahead.",
    "I am an invisible man, not because of any biochemical accident.",
    "It was love at first sight.",
    "As Gregor Samsa awoke one morning from uneasy dreams, he found himself transformed.",
    "You don't know about me without you have read a book by the name of The Adventures of Tom Sawyer.",
    "I am doomed to remember a boy with a wrecked voice.",
    "It was a pleasure to burn.",
    "In my younger and more vulnerable years, my father gave me advice.",
    "I write this sitting in the kitchen sink.",
    "Call me Ishmael.",
    "It was the afternoon of my one hundred and forty-first birthday.",
    "Once upon a time, in a far away land, there lived a girl who dreamed of stars.",
    "The owl and the pussycat went to sea in a beautiful pea green boat.",
    "There was no possibility of taking a walk that day.",
    "It was a bright cold day in April, and the clocks were striking thirteen.",
    "Somewhere in La Mancha, in a place whose name I care not to remember.",
    "Last night I dreamt I went to Manderley again.",
    "You better not never tell nobody but what I'm about to tell you was all true.",
    "The past is a foreign country; they do things differently there.",
    "Whether I shall turn out to be the hero of my own life depends on these pages.",
    "Happy families are all alike; each unhappy family is unhappy in its own way."
  ],
  History: [
    "The only thing we learn from history is that we learn nothing from history.",
    "Those who cannot remember the past are condemned to repeat it.",
    "The past cannot be changed. The future is yet in your power.",
    "History will be kind to me for I intend to write it.",
    "The blood of the covenant is thicker than the water of the womb.",
    "All of history is the endless competition between factions, each of which claims to act in the name of the people.",
    "History is written by the victors.",
    "The only way to understand the future is to look back at the past.",
    "Who controls the past controls the future. Who controls the present controls the past.",
    "The most important thing in life is to have great friends and to earn their trust.",
    "You cannot step into the same river twice, for fresh waters are ever flowing in.",
    "In reading great literature I become a thousand men and yet remain myself.",
    "History is the witness that testifies to the passing of time.",
    "The historian is a prophet looking backwards.",
    "There is nothing new under the sun.",
    "History is philosophy teaching by examples.",
    "Every generation imagines itself to be more intelligent than the one that went before it.",
    "The past speaks to us in a thousand voices, warning and comforting, restraining and encouraging.",
    "History is not a burden on the memory but an illumination of the soul.",
    "We do not learn from history; we only learn that we do not learn from history.",
    "History is a set of lies agreed upon.",
    "The great events of the world are not battles, sieges, or migrations.",
    "History is full of interesting characters and full of interesting problems to solve.",
    "History teaches us that history teaches us nothing.",
    "Our ignorance of history makes us libel our own times.",
    "The only history that is worth a damn is the history we make today.",
    "History has its eyes on you.",
    "To live is to choose; but to choose well, one must know oneself and the world.",
    "The historical figure is both a product and a prisoner of their time.",
    "What we do today echoes in eternity."
  ],
  Spirituality: [
    "The wound is the place where the Light enters you.",
    "Stop acting so small. You are the universe in ecstatic motion.",
    "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.",
    "When you realize there is nothing lacking, the whole world belongs to you.",
    "The mind is everything. What you think, you become.",
    "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
    "Peace comes from within. Do not seek it without.",
    "Knowing others is intelligence; knowing yourself is true wisdom.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "In a gentle way, you can shake the world.",
    "Let yourself be silently drawn by the strange pull of what you really love.",
    "Every morning brings new potential, but only if we are willing to listen.",
    "The obstacle is the path.",
    "What lies behind us and what lies before us are tiny matters.",
    "The flower that blooms in adversity is the most rare and beautiful of all.",
    "You can't calm the storm, so stop trying. What you can do is calm yourself. The storm will pass.",
    "I am not afraid of where I've been. I'm afraid of where I haven't gone.",
    "The only person you are destined to become is the person you decide to be.",
    "If the only prayer you say in your whole life is 'thank you,' that would suffice.",
    "It is during our darkest moments that we must focus to see the light.",
    "There is a light in this world. A healing spirit more powerful than any darkness.",
    "When you change the way you look at things, the things you look at change.",
    "Wherever you are, be all there.",
    "The secret is to care.",
    "Do what you feel in your heart to be right – for you'll be criticized anyway.",
    "And now here is my secret, a very simple secret: It is only with the heart that one can see rightly.",
    "In this moment, right now, you are exactly where you need to be.",
    "Your cells are changing every second; you are never the same person you were a moment ago.",
    "God can be realized through all paths.",
    "The soul always knows what to do to heal itself. The challenge is to silence the mind."
  ]
};

const AUTHORS_DATA = [
  { name: "Socrates", profession: "Philosopher", country: "Greece", birth: "470 BC", death: "399 BC" },
  { name: "Plato", profession: "Philosopher", country: "Greece", birth: "428 BC", death: "348 BC" },
  { name: "Aristotle", profession: "Philosopher", country: "Greece", birth: "384 BC", death: "322 BC" },
  { name: "Confucius", profession: "Philosopher", country: "China", birth: "551 BC", death: "479 BC" },
  { name: "Lao Tzu", profession: "Philosopher", country: "China", birth: "600 BC", death: "Unknown" },
  { name: "Marcus Aurelius", profession: "Philosopher & Emperor", country: "Roman Empire", birth: "121", death: "180" },
  { name: "Seneca", profession: "Philosopher", country: "Roman Empire", birth: "4 BC", death: "65 AD" },
  { name: "Galileo Galilei", profession: "Physicist", country: "Italy", birth: "1564", death: "1642" },
  { name: "Isaac Newton", profession: "Physicist", country: "England", birth: "1643", death: "1727" },
  { name: "Marie Curie", profession: "Scientist", country: "Poland-France", birth: "1867", death: "1934" },
  { name: "Albert Einstein", profession: "Physicist", country: "Germany", birth: "1879", death: "1955" },
  { name: "Niels Bohr", profession: "Physicist", country: "Denmark", birth: "1885", death: "1962" },
  { name: "Richard Feynman", profession: "Physicist", country: "USA", birth: "1918", death: "1988" },
  { name: "Carl Sagan", profession: "Astronomer", country: "USA", birth: "1934", death: "1996" },
  { name: "Stephen Hawking", profession: "Physicist", country: "England", birth: "1942", death: "2018" },
  { name: "Steve Jobs", profession: "Entrepreneur", country: "USA", birth: "1955", death: "2011" },
  { name: "Bill Gates", profession: "Entrepreneur", country: "USA", birth: "1955", death: "Present" },
  { name: "Warren Buffett", profession: "Investor", country: "USA", birth: "1930", death: "Present" },
  { name: "Oprah Winfrey", profession: "Media Mogul", country: "USA", birth: "1954", death: "Present" },
  { name: "Elon Musk", profession: "Entrepreneur", country: "USA", birth: "1971", death: "Present" },
  { name: "Muhammad Ali", profession: "Boxer", country: "USA", birth: "1942", death: "2016" },
  { name: "Serena Williams", profession: "Tennis Player", country: "USA", birth: "1981", death: "Present" },
  { name: "Michael Jordan", profession: "Basketball Player", country: "USA", birth: "1963", death: "Present" },
  { name: "Usain Bolt", profession: "Sprinter", country: "Jamaica", birth: "1986", death: "Present" },
  { name: "William Shakespeare", profession: "Playwright", country: "England", birth: "1564", death: "1616" },
  { name: "Jane Austen", profession: "Novelist", country: "England", birth: "1775", death: "1817" },
  { name: "Mark Twain", profession: "Writer", country: "USA", birth: "1835", death: "1910" },
  { name: "Leo Tolstoy", profession: "Novelist", country: "Russia", birth: "1828", death: "1910" },
  { name: "Charles Dickens", profession: "Novelist", country: "England", birth: "1812", death: "1870" },
  { name: "George Orwell", profession: "Novelist", country: "England", birth: "1903", death: "1950" },
  { name: "Napoleon Bonaparte", profession: "Military Commander", country: "France", birth: "1769", death: "1821" },
  { name: "Winston Churchill", profession: "Prime Minister", country: "England", birth: "1874", death: "1965" },
  { name: "Abraham Lincoln", profession: "President", country: "USA", birth: "1809", death: "1865" },
  { name: "Thomas Jefferson", profession: "President", country: "USA", birth: "1743", death: "1826" },
  { name: "Martin Luther King Jr.", profession: "Civil Rights Leader", country: "USA", birth: "1929", death: "1968" },
  { name: "Mahatma Gandhi", profession: "Independence Leader", country: "India", birth: "1869", death: "1948" },
  { name: "Nelson Mandela", profession: "Anti-apartheid Leader", country: "South Africa", birth: "1918", death: "2013" },
  { name: "Thich Nhat Hanh", profession: "Monk", country: "Vietnam", birth: "1926", death: "2022" },
  { name: "Dalai Lama", profession: "Spiritual Leader", country: "Tibet", birth: "1935", death: "Present" },
  { name: "Deepak Chopra", profession: "Wellness Expert", country: "USA", birth: "1946", death: "Present" },
  { name: "Wayne Dyer", profession: "Self-help Author", country: "USA", birth: "1940", death: "2015" },
  { name: "Brené Brown", profession: "Researcher", country: "USA", birth: "1965", death: "Present" },
  { name: "Maya Angelou", profession: "Poet", country: "USA", birth: "1928", death: "2014" },
  { name: "Tony Robbins", profession: "Motivational Speaker", country: "USA", birth: "1960", death: "Present" },
  { name: "Rumi", profession: "Sufi Poet", country: "Persia", birth: "1207", death: "1273" },
  { name: "Buddha", profession: "Spiritual Teacher", country: "Nepal", birth: "563 BC", death: "483 BC" },
  { name: "Osho", profession: "Spiritual Mystic", country: "India", birth: "1931", death: "1990" },
  { name: "Friedrich Nietzsche", profession: "Philosopher", country: "Germany", birth: "1844", death: "1900" },
  { name: "Jean-Paul Sartre", profession: "Philosopher", country: "France", birth: "1905", death: "1980" },
  { name: "Simone Weil", profession: "Philosopher", country: "France", birth: "1909", death: "1943" },
  { name: "Albert Camus", profession: "Philosopher", country: "France", birth: "1913", death: "1960" }
];

const CATEGORIES = Object.keys(QUOTES_DATA);